### ISSUE TITLE
¿URL no existe?

### ISSUE THREAD

**Issue by Villanuevand** [JuanDelgadillo/angular2-pokedex#1]
Al copiar la url de algún determinado pokemón, esta lanza un 404... 
Acá un ejemplo: 
**_Pokemon**_: Bulbasaur.
**_URL**_ :[http://juandelgadillo.github.io/angular2-pokedex/pokemon/Bulbasaur](http://juandelgadillo.github.io/angular2-pokedex/pokemon/Bulbasaur)

![Imagen de referencia](http://i.imgur.com/Mr7rCt5.png)

**Comment by JuanDelgadillo** [comment]
Solventado con la estrategia de localización Hash como provider en Angular 2 RC5
